"""Official brand domains used for impersonation detection.

Suffix matching is used: a host is official if it equals a listed domain
or is a subdomain of one. User-content hosts (github.io, etc.) are never
treated as official brand properties even when the platform itself is real.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Brand:
    name: str
    aliases: tuple[str, ...]
    domains: tuple[str, ...]
    category: str


# Hosts that anyone can publish on. Brand keywords here are almost always phishing.
USER_CONTENT_SUFFIXES: tuple[str, ...] = (
    "github.io",
    "githubusercontent.com",
    "gitlab.io",
    "netlify.app",
    "vercel.app",
    "web.app",
    "firebaseapp.com",
    "web.app",
    "herokuapp.com",
    "glitch.me",
    "pages.dev",
    "workers.dev",
    "azurestaticapps.net",
    "blob.core.windows.net",
    "z13.web.core.windows.net",
    "web.core.windows.net",
    "cloudfront.net",
    "s3.amazonaws.com",
    "s3-website.amazonaws.com",
    "storage.googleapis.com",
    "appspot.com",
    "ngrok.io",
    "ngrok.app",
    "trycloudflare.com",
    "pages.dev",
    "webflow.io",
    "carrd.co",
    "weebly.com",
    "wixsite.com",
    "wordpress.com",
    "blogspot.com",
    "blogspot.gr",
    "sites.google.com",
    "duckdns.org",
    "hopto.org",
    "no-ip.org",
    "ddns.net",
)

# URL shorteners: expand mentally as "hidden destination".
SHORTENER_HOSTS: frozenset[str] = frozenset(
    {
        "bit.ly",
        "bitly.com",
        "tinyurl.com",
        "t.co",
        "goo.gl",
        "ow.ly",
        "is.gd",
        "buff.ly",
        "rebrand.ly",
        "cutt.ly",
        "shorturl.at",
        "tiny.cc",
        "rb.gy",
        "s.id",
        "lnkd.in",
        "aka.ms",  # Microsoft shortener — official but still opaque if abused
        "adf.ly",
        "bc.vc",
        "soo.gd",
        "surl.li",
        "v.gd",
        "trib.al",
    }
)

SUSPICIOUS_TLDS: frozenset[str] = frozenset(
    {
        "xyz",
        "top",
        "click",
        "link",
        "gq",
        "tk",
        "ml",
        "cf",
        "ga",
        "zip",
        "mov",
        "country",
        "rest",
        "fit",
        "work",
        "cam",
        "quest",
        "cfd",
        "sbs",
        "cyou",
        "icu",
        "buzz",
        "monster",
        "lol",
        "pics",
        "vip",
        "win",
        "loan",
        "men",
        "date",
        "review",
        "download",
        "stream",
        "gdn",
        "racing",
        "faith",
        "accountant",
        "science",
        "trade",
        "party",
        "cricket",
        "webcam",
        "support",
        "site",
        "online",
        "shop",
        "store",
        "fun",
        "life",
        "live",
        "world",
        "today",
        "space",
        "website",
        "tech",
        "app",
        "dev",
        "page",
        "info",
        "biz",
        "club",
        "pw",
        "cc",
        "ws",
        "tk",
        "ru",
        "su",
        "cn",
        "top",
    }
)

# High-value phishing keywords in path/query.
CREDENTIAL_KEYWORDS: tuple[str, ...] = (
    "login",
    "signin",
    "sign-in",
    "sign_in",
    "log-in",
    "logon",
    "password",
    "passwd",
    "passwdreset",
    "reset-password",
    "resetpassword",
    "account",
    "verify",
    "verification",
    "secure",
    "update",
    "confirm",
    "validation",
    "authenticate",
    "oauth",
    "sso",
    "mfa",
    "otp",
    "wallet",
    "billing",
    "invoice",
    "payment",
    "recover",
    "unlock",
    "session",
    "credential",
    "webscr",
    "wp-login",
    "owa",
    "autodiscover",
    "office365",
    "o365",
    "microsoft365",
    "onedrive",
    "sharepoint",
)

BRANDS: tuple[Brand, ...] = (
    Brand(
        name="Microsoft",
        aliases=(
            "microsoft",
            "microsoftonline",
            "microsoft365",
            "office365",
            "office",
            "outlook",
            "hotmail",
            "onedrive",
            "sharepoint",
            "azure",
            "xbox",
            "skype",
            "teams",
            "bing",
            "msn",
            "windows",
            "visualstudio",
            "vsstudio",
            "msft",
            "msonline",
            "office365",
            "o365",
            "msonline",
            "microsoftonline",
            "office365",
        ),
        domains=(
            "microsoft.com",
            "microsoftonline.com",
            "microsoftonline-p.com",
            "microsoft365.com",
            "office.com",
            "office365.com",
            "office.net",
            "outlook.com",
            "live.com",
            "hotmail.com",
            "msn.com",
            "azure.com",
            "azure.net",
            "windows.net",
            "windows.com",
            "windowsazure.com",
            "azurewebsites.net",
            "visualstudio.com",
            "skype.com",
            "xbox.com",
            "xboxlive.com",
            "bing.com",
            "onedrive.com",
            "sharepoint.com",
            "1drv.ms",
            "aka.ms",
            "msft.net",
            "microsoft.net",
            "s-microsoft.com",
            "microsoftstore.com",
            "yammer.com",
            "powerbi.com",
            "dynamics.com",
            "cloudapp.net",
            "trafficmanager.net",
            "azureedge.net",
            "microsoftpersonalcontent.com",
            "officeapps.live.com",
            "microsoft.us",
            "microsoftonline.us",
            "office365.us",
            "microsoftcloud.com",
            "msecnd.net",
            "azure-api.net",
            "visualstudio.com",
            "vsassets.io",
            "msidentity.com",
            "msauth.net",
            "msftauth.net",
            "microsoftonline.de",
            "windowsazure.cn",
            "azure.cn",
        ),
        category="tech",
    ),
    Brand(
        name="GitHub",
        aliases=("github", "ghpages"),
        domains=("github.com", "github.blog", "githubstatus.com", "gh.io"),
        category="tech",
    ),
    Brand(
        name="LinkedIn",
        aliases=("linkedin", "linked-in"),
        domains=("linkedin.com", "licdn.com", "lnkd.in"),
        category="social",
    ),
    Brand(
        name="Google",
        aliases=("google", "gmail", "youtube", "youtu", "gstatic", "gdrive", "gsuite", "workspace"),
        domains=(
            "google.com",
            "google.gr",
            "googleapis.com",
            "gstatic.com",
            "gmail.com",
            "youtube.com",
            "youtu.be",
            "ytimg.com",
            "withgoogle.com",
            "googleusercontent.com",
            "googledrive.com",
            "googlemail.com",
            "google.co.uk",
            "chrome.com",
            "android.com",
            "chromium.org",
            "google.net",
            "google",
        ),
        category="tech",
    ),
    Brand(
        name="Apple",
        aliases=("apple", "icloud", "itunes", "appstore", "icloudmail", "macbook", "iphone"),
        domains=(
            "apple.com",
            "icloud.com",
            "icloud.com.cn",
            "apple.co",
            "mzstatic.com",
            "cdn-apple.com",
            "apple-cloudkit.com",
            "me.com",
            "mac.com",
        ),
        category="tech",
    ),
    Brand(
        name="Amazon",
        aliases=("amazon", "aws", "kindle", "primevideo", "amazonses", "awscloud"),
        domains=(
            "amazon.com",
            "amazon.gr",
            "amazon.co.uk",
            "amazon.de",
            "amazonaws.com",
            "amazon.co.jp",
            "aws.amazon.com",
            "amazon.dev",
        ),
        category="tech",
    ),
    Brand(
        name="Meta",
        aliases=("facebook", "instagram", "whatsapp", "meta", "fb", "messenger"),
        domains=(
            "facebook.com",
            "fb.com",
            "fbcdn.net",
            "instagram.com",
            "cdninstagram.com",
            "whatsapp.com",
            "whatsapp.net",
            "messenger.com",
            "meta.com",
            "oculus.com",
        ),
        category="social",
    ),
    Brand(
        name="PayPal",
        aliases=("paypal", "pay-pal", "paypa1"),
        domains=("paypal.com", "paypal.me", "paypalobjects.com", "paypal.co.uk"),
        category="finance",
    ),
    Brand(
        name="Stripe",
        aliases=("stripe",),
        domains=("stripe.com", "stripe.network"),
        category="finance",
    ),
    Brand(
        name="Visa",
        aliases=("visa", "visacard"),
        domains=("visa.com", "visa.gr"),
        category="finance",
    ),
    Brand(
        name="Mastercard",
        aliases=("mastercard", "master-card"),
        domains=("mastercard.com", "mastercard.gr"),
        category="finance",
    ),
    Brand(
        name="American Express",
        aliases=("americanexpress", "amex"),
        domains=("americanexpress.com", "amex.com"),
        category="finance",
    ),
    Brand(
        name="Coinbase",
        aliases=("coinbase", "coin-base"),
        domains=("coinbase.com", "coinbase.org"),
        category="crypto",
    ),
    Brand(
        name="Binance",
        aliases=("binance", "bnb"),
        domains=("binance.com", "binance.us", "binance.org"),
        category="crypto",
    ),
    Brand(
        name="Kraken",
        aliases=("kraken",),
        domains=("kraken.com",),
        category="crypto",
    ),
    Brand(
        name="Netflix",
        aliases=("netflix", "netfllx"),
        domains=("netflix.com", "nflxext.com", "nflximg.net"),
        category="media",
    ),
    Brand(
        name="Spotify",
        aliases=("spotify",),
        domains=("spotify.com", "scdn.co", "spotifycdn.com"),
        category="media",
    ),
    Brand(
        name="X / Twitter",
        aliases=("twitter", "xcorp"),
        domains=("twitter.com", "x.com", "twimg.com", "t.co"),
        category="social",
    ),
    Brand(
        name="TikTok",
        aliases=("tiktok", "douyin"),
        domains=("tiktok.com", "tiktokcdn.com", "musical.ly"),
        category="social",
    ),
    Brand(
        name="Discord",
        aliases=("discord", "discordapp"),
        domains=("discord.com", "discordapp.com", "discord.gg"),
        category="social",
    ),
    Brand(
        name="Steam",
        aliases=("steam", "steampowered", "steamcommunity"),
        domains=("steampowered.com", "steamcommunity.com", "steamstatic.com", "valvesoftware.com"),
        category="gaming",
    ),
    Brand(
        name="PlayStation",
        aliases=("playstation", "playstationnetwork", "psn", "sony"),
        domains=("playstation.com", "sony.com", "sonyentertainmentnetwork.com"),
        category="gaming",
    ),
    Brand(
        name="Dropbox",
        aliases=("dropbox",),
        domains=("dropbox.com", "dropboxusercontent.com", "dropbox.tech"),
        category="tech",
    ),
    Brand(
        name="Adobe",
        aliases=("adobe", "acrobat", "photoshop", "creativecloud"),
        domains=("adobe.com", "adobe.io", "adobelogin.com", "typekit.net"),
        category="tech",
    ),
    Brand(
        name="Zoom",
        aliases=("zoom", "zoomus"),
        domains=("zoom.us", "zoom.com", "zoomgov.com"),
        category="tech",
    ),
    Brand(
        name="DocuSign",
        aliases=("docusign", "docu-sign"),
        domains=("docusign.com", "docusign.net"),
        category="tech",
    ),
    Brand(
        name="Slack",
        aliases=("slack",),
        domains=("slack.com", "slack-edge.com"),
        category="tech",
    ),
    Brand(
        name="Chase",
        aliases=("chase", "chasebank", "jpmorgan"),
        domains=("chase.com", "jpmorganchase.com", "jpmorgan.com"),
        category="finance",
    ),
    Brand(
        name="Bank of America",
        aliases=("bankofamerica", "bofa", "bankamerica"),
        domains=("bankofamerica.com", "bofa.com"),
        category="finance",
    ),
    Brand(
        name="Wells Fargo",
        aliases=("wellsfargo", "wells-fargo"),
        domains=("wellsfargo.com",),
        category="finance",
    ),
    Brand(
        name="Revolut",
        aliases=("revolut",),
        domains=("revolut.com",),
        category="finance",
    ),
    Brand(
        name="Wise",
        aliases=("wise", "transferwise"),
        domains=("wise.com", "transferwise.com"),
        category="finance",
    ),
    Brand(
        name="National Bank of Greece",
        aliases=("nbg", "nbgbank", "ethniki", "nationalbank"),
        domains=("nbg.gr", "nbgbank.gr"),
        category="finance",
    ),
    Brand(
        name="Eurobank",
        aliases=("eurobank",),
        domains=("eurobank.gr", "eurobank.eu"),
        category="finance",
    ),
    Brand(
        name="Piraeus Bank",
        aliases=("piraeus", "piraeusbank", "trapezapeiraios"),
        domains=("piraeusbank.gr", "piraeus-bank.gr"),
        category="finance",
    ),
    Brand(
        name="Alpha Bank",
        aliases=("alphabank", "alpha-bank"),
        domains=("alpha.gr", "alphabank.gr"),
        category="finance",
    ),
    Brand(
        name="gov.gr",
        aliases=("govgr", "taxisnet", "aade", "gsis"),
        domains=("gov.gr", "aade.gr", "gsis.gr", "taxisnet.gr"),
        category="government",
    ),
    Brand(
        name="IRSgov",
        aliases=("irs", "internalrevenue"),
        domains=("irs.gov",),
        category="government",
    ),
    Brand(
        name="DHL",
        aliases=("dhl", "dhl-express"),
        domains=("dhl.com", "dhl.gr"),
        category="logistics",
    ),
    Brand(
        name="UPS",
        aliases=("ups", "ups-tracking"),
        domains=("ups.com",),
        category="logistics",
    ),
    Brand(
        name="FedEx",
        aliases=("fedex", "federalexpress"),
        domains=("fedex.com",),
        category="logistics",
    ),
    Brand(
        name="Vodafone",
        aliases=("vodafone",),
        domains=("vodafone.gr", "vodafone.com"),
        category="telecom",
    ),
    Brand(
        name="Cosmote",
        aliases=("cosmote", "cosmoteid"),
        domains=("cosmote.gr", "cosmotetv.gr"),
        category="telecom",
    ),
    Brand(
        name="Nova",
        aliases=("nova", "nova-gr"),
        domains=("nova.gr",),
        category="telecom",
    ),
    Brand(
        name="WhatsApp",
        aliases=("whatsapp", "wa-me"),
        domains=("whatsapp.com", "whatsapp.net", "wa.me"),
        category="social",
    ),
    Brand(
        name="Telegram",
        aliases=("telegram", "telegramorg"),
        domains=("telegram.org", "t.me", "telegram.me"),
        category="social",
    ),
)


def host_matches_suffix(host: str, suffix: str) -> bool:
    host = host.lower().rstrip(".")
    suffix = suffix.lower().rstrip(".")
    return host == suffix or host.endswith("." + suffix)


def is_user_content_host(host: str) -> bool:
    return any(host_matches_suffix(host, s) for s in USER_CONTENT_SUFFIXES)


def official_brand_for_host(host: str) -> Brand | None:
    """Return the brand if host is an official property (not user-content)."""
    if is_user_content_host(host):
        return None
    for brand in BRANDS:
        if any(host_matches_suffix(host, d) for d in brand.domains):
            return brand
    return None
